[project]
name = "agenda"
version = "0.1.0"
description = ""
authors = [
    {name = "Marcelo de Campos"}
]
requires-python = ">=3.13,<4.0"
dependencies = [
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "alembic (>=1.19.2,<2.0.0)",
    "sqlalchemy[asyncio] (>=2.0.52,<3.0.0)",
    "psycopg[binary] (>=3.3.5,<4.0.0)",
    "structlog (>=26.1.0,<27.0.0)",
    "fastapi (>=0.135.1,<1.0.0)",
    "uvicorn[standard] (>=0.42.0,<1.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "python-multipart (>=0.0.20,<0.1.0)"
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
pytest-cov = "^6.0"
ruff = "^0.8"
Faker = "^30.8"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.coverage.run]
source = ["src/agenda"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

