"use client";

import { App, AutoComplete, Button, Card, Form, Input, Modal, Select, Typography, message } from "antd";
import { SearchOutlined } from "@ant-design/icons";
import { useState } from "react";

import { AdminSidebar } from "@/components/admin/admin-sidebar";
import { useAuth } from "../../auth-provider";

type FederativeUnit = { id: string; name: string; abbreviation: string };

function formatPostalCode(value: string | undefined): string { const digits = (value ?? "").replace(/\D/g, "").slice(0, 8); return digits.replace(/^(\d{2})(\d)/, "$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/, "$1.$2-$3"); }

export default function LayoutLabPage() {
  const { apiFetch } = useAuth();
  const [open, setOpen] = useState(false);
  const [form] = Form.useForm();
  const [messageApi, contextHolder] = message.useMessage();
  const [federativeUnits, setFederativeUnits] = useState<FederativeUnit[]>([]);
  const [municipalityOptions, setMunicipalityOptions] = useState<{ value: string; label: string }[]>([]);
  const groups = [{ id: "layout-lab-group-tables", label: "Tabelas", items: [{ id: "layout-lab-nav-gender", label: "Gênero", href: "/admin/genders" }, { id: "layout-lab-nav-locality", label: "Localidade", href: "/admin/localities" }] }, { id: "layout-lab-group-people", label: "Pessoa", items: [{ id: "layout-lab-nav-person", label: "Pessoa física", href: "/admin/people" }, { id: "layout-lab-nav-company", label: "Pessoa jurídica", href: "/admin/people" }] }, { id: "layout-lab-group-layout", label: "Elementos de layout", items: [{ id: "layout-lab-nav-buttons", label: "Botões", href: "/admin/button-lab" }, { id: "layout-lab-nav-current", label: "Laboratório de layout", href: "/admin/layout-lab", active: true }, { id: "layout-lab-nav-address", label: "Diálogo de endereço", href: "/admin/layout-lab/address-dialog" }] }];
  async function openDialog() { setOpen(true); if (federativeUnits.length === 0) { const response = await apiFetch("http://localhost:8081/admin/federative-units"); if (response.ok) { setFederativeUnits((await response.json()) as FederativeUnit[]); return; } messageApi.error("Não foi possível carregar as UFs. Faça login como administrador."); } }
  function close() { setOpen(false); form.resetFields(); setMunicipalityOptions([]); }
  async function lookupCep(value: string) { const digits = value.replace(/\D/g, ""); if (digits.length !== 8) { messageApi.error("Informe um CEP com 8 dígitos."); return; } const response = await fetch(`http://localhost:8081/public/addresses/cep/${digits}`); if (!response.ok) { messageApi.error("CEP não encontrado."); return; } const address = await response.json() as { street_name?: string; complement?: string; neighborhood?: string; municipality?: string; federative_unit?: string; postal_code: string }; const unit = federativeUnits.find((item) => item.abbreviation === address.federative_unit); form.setFieldsValue({ postal_code: formatPostalCode(address.postal_code), street_name: address.street_name, complement: address.complement, neighborhood: address.neighborhood, municipality: address.municipality, state: unit?.id }); messageApi.success("Endereço localizado."); }
  async function searchMunicipalities(value: string) { const unitId = form.getFieldValue("state"); if (!unitId) { setMunicipalityOptions([]); return; } if (value.trim().length < 3) { setMunicipalityOptions([]); return; } const response = await apiFetch(`http://localhost:8081/admin/municipalities?search=${encodeURIComponent(value.trim())}&federative_unit_id=${encodeURIComponent(unitId)}`); if (!response.ok) return; const municipalities = await response.json() as { name: string }[]; setMunicipalityOptions(municipalities.map((municipality) => ({ value: municipality.name, label: municipality.name }))); }
  function lookupIcon() { return <span id="layout-address-postal-search" className="address-dialog-cep-icon" role="button" tabIndex={0} aria-label="Pesquisar CEP" onClick={() => void lookupCep(form.getFieldValue("postal_code") ?? "")}><SearchOutlined /></span>; }
  return <App><main id="layout-lab-page" className="admin-area">{contextHolder}<AdminSidebar id="layout-lab-sidebar" groups={groups} /><section id="layout-lab-content" className="admin-content"><Typography.Title id="layout-lab-title" level={2}>Elementos de layout</Typography.Title><Typography.Paragraph id="layout-lab-description" type="secondary">Exemplos interativos para validar usabilidade. Nenhum exemplo persiste dados.</Typography.Paragraph><Card id="address-dialog-example" title="Diálogo de endereço" style={{ maxWidth: 520 }}><Typography.Paragraph id="address-dialog-example-description">Formulário modal para validar a experiência de inclusão de endereço.</Typography.Paragraph><Button id="address-dialog-example-open" type="primary" onClick={() => void openDialog()}>Incluir endereço</Button></Card><Modal title="Incluir endereço" open={open} onCancel={close} footer={null} destroyOnHidden><Form id="layout-address-form" form={form} layout="vertical" onFinish={() => { close(); messageApi.success("Exemplo validado localmente; nenhum dado foi salvo."); }}><Form.Item label="CEP" name="postal_code" normalize={formatPostalCode} rules={[{ required: true, message: "Informe o CEP." }]}><Input id="layout-address-postal-code" maxLength={10} className="address-dialog-cep-input" suffix={lookupIcon()} autoComplete="off" data-lpignore="true" data-1p-ignore="true" data-bwignore="true" data-form-type="other" /></Form.Item><Form.Item label="UF" name="state" rules={[{ required: true, message: "Selecione a UF antes do município." }]}><Select id="layout-address-state" options={federativeUnits.map((unit) => ({ value: unit.id, label: `${unit.abbreviation} - ${unit.name}` }))} onChange={() => { form.setFieldValue("municipality", undefined); setMunicipalityOptions([]); }} /></Form.Item><Form.Item label="Município" name="municipality" rules={[{ required: true, message: "Informe o município." }]}><AutoComplete id="layout-address-municipality" options={municipalityOptions} onSearch={(value) => void searchMunicipalities(value)} placeholder="Selecione a UF e digite pelo menos 3 letras" /></Form.Item><Form.Item label="Logradouro" name="street_name" rules={[{ required: true, message: "Informe o logradouro." }]}><Input id="layout-address-street" /></Form.Item><Form.Item label="Número" name="number"><Input id="layout-address-number" /></Form.Item><Form.Item label="Complemento" name="complement"><Input id="layout-address-complement" /></Form.Item><Form.Item label="Bairro" name="neighborhood"><Input id="layout-address-neighborhood" /></Form.Item><Button id="layout-address-submit" type="primary" htmlType="submit">Validar endereço</Button></Form></Modal></section></main></App>;
}
